// src/app/terms/page.tsx
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="bg-slate-50 min-h-screen">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold text-slate-800 mb-6">Terms and Conditions</h1>
        <div className="bg-white p-8 rounded-lg shadow-md space-y-4 text-slate-600">
          <h2 className="text-xl font-semibold text-slate-700">1. Introduction</h2>
          {/* CORRECTED LINE */}
          <p>Welcome to Legacy Linter (&quot;Application&quot;, &quot;Service&quot;). These Terms and Conditions govern your use of our application, which is a project for the IBM Co-Creating with GPT-5 Hackathon. By accessing or using the Service, you agree to be bound by these Terms.</p>

          <h2 className="text-xl font-semibold text-slate-700">2. Use of Service</h2>
          <p>This application is provided as-is for demonstration purposes. You agree not to misuse the service or help anyone else to do so. The service is intended to analyze and refactor code snippets you provide.</p>

          <h2 className="text-xl font-semibold text-slate-700">3. User Content</h2>
          <p>You retain full ownership of the code you submit. By using the service, you grant us a temporary, non-exclusive license to process your code in order to provide you with the refactored output. We do not store your code after the session is complete.</p>
          
          <h2 className="text-xl font-semibold text-slate-700">4. Disclaimer</h2>
          <p>The output generated by the AI is for informational purposes only and is not guaranteed to be error-free, secure, or fit for production use. Always review and test AI-generated code thoroughly before implementation.</p>

          <div className="text-center pt-4">
            <Link href="/auth" className="text-sky-600 hover:underline font-semibold">
              &larr; Back to Sign Up
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}